### ISSUE TITLE
Group datasets together into sets for bulk updating

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-data-operations#189]
Group datasets together into sets for bulk moves from staging to production
1) zoning datasets
2) DCM datasets
3) Districts
Need to get list of datasets from GIS that should be grouped into these sets

**Comment by croswell81** [comment]
@AmandaDoyle this is the list of datasets for each group. We should think about the admin/political districts as well since they are updated together with each release of Bytes (e.g. 21A, 21B, etc.)

Zoning:
-dcp_commercial_overlays
-dcp_limited_height_districts
-dcp_sidewalk_cafes
-dcp_special_purpose_districts
-dcp_special_purpose_subdistricts
-dcp_zoning_districts
-dcp_zoning_map_amendments

DCM
-dcp_dcm
-dcp_dcm_arterials_major_streets
-dcp_dcm_city_map_alterations
-dcp_dcm_street_centerline
-dcp_dcm_street_name_changes_areas
-dcp_dcm_street_name_changes_lines
-dcp_dcm_street_name_changes_points

**Comment by SPTKL** [comment]
complete
